apiVersion: batch/v1
kind: Job
metadata:
  name: git-init
  namespace: playlister
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: git-init
        image: alpine/git:latest
        command:
        - /bin/sh
        - -c
        - |
          # Setup git config
          git config --global user.name "$GIT_USER_NAME"
          git config --global user.email "$GIT_USER_EMAIL"

          # Setup SSH key for git
          mkdir -p ~/.ssh
          echo "$GIT_SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

          # Clone or initialize repo
          cd /data
          if [ ! -d ".git" ]; then
            git clone "$GIT_URL" .
          else
            git pull origin main
          fi
        env:
        - name: GIT_URL
          valueFrom:
            secretKeyRef:
              name: playlister-secrets
              key: git-url
        - name: GIT_USER_NAME
          valueFrom:
            secretKeyRef:
              name: playlister-secrets
              key: git-user-name
        - name: GIT_USER_EMAIL
          valueFrom:
            secretKeyRef:
              name: playlister-secrets
              key: git-user-email
        - name: GIT_SSH_KEY
          valueFrom:
            secretKeyRef:
              name: playlister-secrets
              key: git-ssh-key
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: playlister-data
