apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: playlister

resources:
- namespace.yaml
- pvc.yaml
- git-init-job.yaml
- downloader-cronjob.yaml
# TODO: Add the UI
# - ui-deployment.yaml

secretGenerator:
- name: playlister-secrets
  files:
  - api-key=secrets/api-key.txt
  - git-ssh-key=secrets/id_rsa
  literals:
  - git-url=git@github.com:ian-howell/playlister-data
  - git-user-name=Downloader
  - git-user-email=Downloader@example.com
